<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_dipa_model extends CI_Model
{

    public $table = 't_dipa';
    public $id = 'id_dipa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_dipa,no_dipa,tahun_anggaran,pagu,kode_dept,kode_unit_kerja,kode_satker,create_date,nama_dept,nama_unit_kerja,nama_satker');
        $this->datatables->from('v_dipa');
        //add this line for join
        //$this->datatables->join('table2', 't_dipfield = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_dipa/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs waves-effect waves-themed')) . " 
            " . anchor(site_url('t_dipa/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs waves-effect waves-themed')) . " 
                " . anchor(site_url('t_dipa/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-xs waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_dipa');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_dipa')->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_dipa', $q);
        $this->db->or_like('no_dipa', $q);
        $this->db->or_like('tahun_anggaran', $q);
        $this->db->or_like('pagu', $q);
        $this->db->or_like('kode_dept', $q);
        $this->db->or_like('kode_unit_kerja', $q);
        $this->db->or_like('kode_satker', $q);
        $this->db->or_like('create_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dipa', $q);
        $this->db->or_like('no_dipa', $q);
        $this->db->or_like('tahun_anggaran', $q);
        $this->db->or_like('pagu', $q);
        $this->db->or_like('kode_dept', $q);
        $this->db->or_like('kode_unit_kerja', $q);
        $this->db->or_like('kode_satker', $q);
        $this->db->or_like('create_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_dipa_model.php */
/* Location: ./application/models/T_dipa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-17 06:01:42 */
/* http://harviacode.com */